### ISSUE TITLE
Keyboard layout switching

### ISSUE THREAD

**Issue by trsrm** [gkpln3/CapsLockNoDelay#3] opened 2021-02-10 11:31 UTC
I'm using CapsLock for switching keyboard layout.

With CapsLockNoDelay it switches the layout AND switches the capitalization both.

But, switching the capitalization is not expected in this case.

**Comment by gkpln3** [comment] 2021-02-10 13:55
What you say sounds reasonable.
But I'm not quite sure what is the expected behavior in this case.
How do you usually switch capitalizations?

**Comment by trsrm** [comment] 2021-02-10 14:11
Actually, I don't switch capitalization, I'm just using the "Shift" key. 
But MacOS allows doing it by long-press the "CapsLock".

https://support.apple.com/guide/mac-help/type-language-mac-input-sources-mchlp1406/mac

**Comment by gkpln3** [comment] 2021-02-10 19:19
If so, doesn't it make this whole utility useless for you?
The goal of this utility is exactly to remove the short delay MacOS requires you to wait while holding the caps lock key for it to activate.

**Comment by trsrm** [comment] 2021-02-10 20:05
I'm using CapsLock to switch keyboard layout (switch typing language).
But, MacOS has a stupid annoying "feature" that adds a delay to CapsLock key-press (no matter what action is mapped to it).

I tried your tool and it removes the delay, so the keyboard layout switches instantly.
But, **also** it changes the capitalization on key-press - that is unexpected.
I just want to remove the key-press delay.

**Comment by gkpln3** [comment] 2021-02-12 13:28
Oh I see what you mean, I will look into it.
Thanks!

**Comment by anderdeath** [comment] 2022-05-27 11:39
Is it expected to be fixed? This script is extremely useful but having capitalisation of the letters triggered simultaneously quite kills the script usefulness.

**Comment by gkpln3** [comment] 2022-06-22 09:13
I've tried to reproduce this issue with version 1.0.3
The program seems to work as expected.
Can you guys confirm if this is still an issue or not?

**Comment by anderdeath** [comment] 2022-06-22 09:15
Yes, it is still an issue, reproduced very often. Using Monterey 12.4

**Comment by XInTheDark** [comment] 2022-06-23 07:45
> Yes, it is still an issue, reproduced very often. Using Monterey 12.4

Me too!

> If so, doesn't it make this whole utility useless for you?
> The goal of this utility is exactly to remove the short delay MacOS requires you to wait while holding the caps lock key for it to activate.

Maybe you could change it so that: 
1. instantly change capitalisation upon pressing
2. if user holds CapsLock for less than 0.5s, do nothing upon release of key
3. else, change capitalisation again.

Seems like an easy implementation.

**Comment by GitSparTV** [comment] 2022-06-29 13:56
Upvote as well. Tried to use capslock for fast switching but Apple has weird delay with the keyboard. Slow keys helps but it affects touch bar.
This extensions works for usual capslock usage but I have it bind to layout switching.
Capslock still exists if you hold it for a long time

Karabiner elements didn't help, so I hope this app could help me

**Comment by wokalek** [comment] 2022-11-05 14:52
Same here, switch both, lang and caps letters

**Comment by renakdup** [comment] 2022-11-07 20:19
have the same bug with Ventura 13.0

**Comment by onelightinthedark** [comment] 2022-11-12 21:02
i'm also on ventura and looking for a similar fix to the problem @trsrm mentioned. i realise that it's not within the scope of what this program is supposed to do, but it comes close to solving an issue a lot of us have. maybe it'll help if i explain in detail.

when pressing <kbd>caps lock</kbd> to switch input sources, there is a very slight delay in detection that frequently causes the switching behaviour to fail. so, if i'm typing in english, and i then immediately hit <kbd>caps lock</kbd> to change the input source to pinyin chinese, and then immediately continue to type, macos doesn't always switch the input source over to the other language. <kbd>caps lock</kbd> should respond just as fast as <kbd>space</kbd> or <kbd>shift</kbd> in this scenario, but it doesn't.

your program seems to fix this problem by eliminating the delay on the <kbd>caps lock</kbd> key press being detected, so the program is indeed working as intended.

for those of us who type quickly in different languages, the actual function of always typing in caps is pretty much useless, but using <kbd>caps lock</kbd> to immediately switch input sources is invaluable.

what others (and i) are asking is: is it possible to add an option in your program to disable the capitalisation-locking part of <kbd>caps lock</kbd>, but still retain the behaviour/mechanism that fixes the delay in the os detecting the key press?

**Comment by gkpln3** [comment] 2022-11-12 21:16
@onelightinthedark Thanks for making this clear, I will try and look a fix for this kind of use, will keep you updated here.

**Comment by gbougiakas** [comment] 2022-11-14 18:47
+1 for this please help us!

**Comment by gkpln3** [comment] 2022-11-22 12:40
I've uploaded a new version that is supposed to fix this, can someone please confirm?

**Comment by gbougiakas** [comment] 2022-11-22 12:46
I can confirm that the new version works great!

**Comment by gkpln3** [comment] 2022-11-22 16:22
Great! closing this issue.

**Comment by onelightinthedark** [comment] 2022-12-08 02:15
> Great! closing this issue.

first, thanks for taking the time to look at this issue and update this.

unfortunately, it's not working for me on ventura 13.0.1.  i checked all the obvious things like making sure the app is running, permissions in security settings, uninstalling and reinstalling, but the behaviour of the caps lock key seems to be unchanged. i still get the delay, and sometimes it toggles caps lock on instead of switching languages (and, as before, sometimes the key does nothing altogether).

it feels like macos is still waiting for the key-up event (not sure how it's technically termed), like it waits for caps lock to be released instead of pressed to decide whether or not to enable caps lock, do nothing, or switch the input language.

in any case, thanks again for taking a look at it. if i can provide logs or something else helpful, just let me know

**Comment by gbougiakas** [comment] 2022-12-08 07:14
To add to the conversation after days of using it I have the exact same
experience on Ventura. It’s not buggy anymore but it also doesn’t seem to
do anything.

**Comment by s-titov** [comment] 2023-02-12 19:13
Any news? I still have caps lock delay, when using it for switching language layout

**Comment by mmatrosov** [comment] 2023-02-15 17:02
I can confirm that the tool seems to be doing nothing under M1 Pro Ventura 13.2 

I have the same use case as the one OP thoroughly described.

**Comment by leni8ec** [comment] 2023-07-22 13:06
I also tried this tool, but it doesn't fix the [issue](https://www.reddit.com/r/mac/comments/ybk6vn/caps_lock_language_switch_delay/) with `Caps Lock` language switching.

Macbook Air M1 - Ventura 13.4.1
Macbook Air M2 - Ventura 13.4.1

**Comment by gkpln3** [comment] 2024-06-21 08:12
Please refer to the new method in the readme file.

**Closed as completed by gkpln3** 2024-06-21 08:12 UTC
Labels: bug

**Comment by leni8ec** [comment] 2024-06-21 12:01
> Please refer to the new method in the readme file.

Unfortunately, in my case, it still doesn't work.. I tried your program again according to the instructions - there is no result. And I also tried a new way, through 'hidutil' - it doesn't work. In both cases, I tried to reboot.
